---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: materials-api-secrets
  namespace: default
spec:
  encryptedData:
    yandex_disk_public_key: AgBVZ1M9czOX+XiC+sbvWWAIrny2HHqoRMFhhIBDG1EQ7e2zY7c+9Ou91I1YX7idYbxDL9dMsRN3dyAGDxN4gd9ekgxQ04y7JBX/8PmFhkp+xEBUkeaY3ssFdBRbCU6Lz8KMEtrWkdEY8KnYsq/XTD3m+OfVKWg0adJ/ldsnF81/mPjbX0pG9toVytaOeFkZFTdZHzEXAR/wBlSZfoaG8QrhgqCI/TWsfaYfy3knv/CaT8HGSW5S83gLZpJGyz8xYDGmYSj6jne5HpU2DFek8IRkO4vnv/MBt9GunTQRyHga/dlymVi6kk3mrmHbGI4JLRCS7/LZOkqDNY17CywZWUQouClCXBToAEk0txfFju0PYqv3E6mKwjuye93NXHLd7wFDRYlXACw7LD0HXuGltw5dzL++iZkuxC4BEWthVRdYXqqjQ90JeghBRV7aO9hrnBBJptSnvJ3IO6U2+ZqlpIoNtmigtwT5ALPkYlrVIzBE04SkE8crlnRHTX3Yo3ha5vT/wf6fbOgI5uXlwW8W1vTuoBKx/i+/aKx6CH7hFr7qHdc1RYcBQsFYQ4qwMVBVI/fdvy3q7shlk+DVXoY2oTIjbiZsZ6f9rx2g83Vo0YX/MxPlNiY0KE0yGcioCZ+B0Q1HICrIH0lm1MIXJ9k+T/uknHzn5U7GaEXPTYzMxTBkWciGTT9paEuHqFwgRBLUGA4XQf8gKg0Xu2DKUPTc7WjO36LsOm760/ygZ9Bh3Btu1oGoqFhnYhg=
  template:
    metadata:
      name: materials-api-secrets
      namespace: default
