apiVersion: v1
kind: Service
metadata:
  name: api-service-primary
  labels:
    {{- include "materials-api.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: production-api
    version: {{ .Values.primary.version | quote }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      name: http

---
{{- if .Values.canary.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: api-service-canary
  labels:
    {{- include "materials-api.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: production-api
    version: {{ .Values.canary.version | quote }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      name: http
{{- end -}}